### ISSUE TITLE
Performance audit

### ISSUE THREAD

**Issue by chrisjaure** [BarCampGreenBay/barcampgb.org-server#7]
Would like someone to perform a performance audit of the machine and tune it up if possible.

**Comment by chrisjaure** [comment]
@mikeputnam It would be cool if you could work your devops magic.

**Comment by mikeputnam** [comment]
Any pre-audit evidence of slowness?

**Comment by chrisjaure** [comment]
CPU is consistently above 15%. I'm not sure if that's because of the compute instance type or if something is using more than it should. Also, the mongodb role starts up 2 instances of mongod for some reason.

**Comment by mikeputnam** [comment]
After looking at the instance, apart from being somewhat memory constrained at 512MB (nodejs is using 25% of that) I couldn't find any glaring performance problems.

Looking into the Google reported CPU metrics I came across this thread that may explain the non-zero cpu floor we are seeing:

"CPU always on 15% on idle server" - https://groups.google.com/forum/#!msg/mongodb-user/9Z7K2oXzGWQ/eGSZFimFgeQJ

...which suggests this trait of mongodb: https://jira.mongodb.org/browse/SERVER-2114

aka mongodb has a non-zero cpu idle.

**Comment by mikeputnam** [comment]
Disabled atime on the mongod /data volume per: http://docs.mongodb.org/manual/administration/production-notes/#recommended-configuration

No measurable change in the Google CPU metric.

**Comment by chrisjaure** [comment]
@mikeputnam in your opinion, would you say this isn't an issue for now?

**Comment by mikeputnam** [comment]
Yes. Given the required components (nodejs/mongo/nginx) all running on the same machine I believe this is a normal performance outcome.
